---
ansible_user: zulu

packages_to_install:
  # Base utils
  - bat
  - build-essential
  - ca-certificates
  - curl
  - git
  - gnupg
  - htop
  - iperf3
  - net-tools
  - nmap
  - python3-pip
  - python3-psutil
  - python3-venv
  - software-properties-common
  - tar
  - tmux
  - traceroute
  - tree
  - unzip
  - vim
  - wget
  - zsh
  # Virtualization
  - bridge-utils
  - cloud-init
  - cloud-utils
  - dnsmasq
  - genisoimage
  - libguestfs-tools
  - libvirt-clients
  - libvirt-daemon-system
  - libvirt-dev
  - qemu-kvm
  - qemu-utils
  - virt-manager
  - virtinst
  # Vagrant deps
  - gcc
  - make
  - ruby-dev

dotfiles_base_dest: "/home/{{ ansible_user }}"
dotfiles_items:
  - { src: ".bashrc", dest_suffix: ".bashrc" }
  - { src: ".vimrc", dest_suffix: ".vimrc" }
  - { src: ".zshrc", dest_suffix: ".zshrc" }
  - { src: ".p10k.zsh", dest_suffix: ".p10k.zsh" }
  - { src: "ruff.toml", dest_suffix: ".config/ruff/ruff.toml" }
  - { src: ".gitconfig", dest_suffix: ".gitconfig" }
  - { src: "settings.json", dest_suffix: ".config/Code/User/settings.json" }

wallpaper_src: "default_wallpaper.jpg" # This path is relative to roles/desktop_settings/files/
wallpaper_dest: "/usr/share/backgrounds/default_wallpaper.jpg"
gnome_background_picture_uri: "'file:///usr/share/backgrounds/default_wallpaper.jpg'"
gnome_background_picture_options: "'fit'"

snap_packages_to_install:
  - { name: "code", classic: true }
  - { name: "postman", classic: false }

gnome_terminal_themes_to_install:
  - macchiato
  - nord

dotfiles_repo: "git@github.com:sydasif/dotfiles.git"
dotfiles_dest: "/home/{{ ansible_user }}/.dotfiles"
