---
- hosts: all
  connection: local
  become: true
  gather_facts: false
  tasks:
    - name: copy dotfiles and config files
      copy:
        src: "{{ item.src }}"
        dest: "{{ dotfiles_base_dest }}/{{ item.dest_suffix }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      loop: "{{ dotfiles_items }}"
