---
- name: Configure Ubuntu system
  hosts: all
  gather_facts: true
  become: true

  pre_tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600 # Update only if cache is older than 1 hour
      changed_when: false
      when: ansible_distribution == 'Ubuntu'

  roles:
    - { role: setup_packages, tags: ["packages"] }
    - { role: setup_dotfiles, tags: ["dotfiles"] }
    - { role: setup_fonts, tags: ["fonts"] }
    - { role: setup_docker, tags: ["docker"] }
    - { role: setup_gnome, tags: ["gnome"] }
