---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install packages
      package:
        name:
          - htop
          - tmux
          - vim
          - python3-psutil
          - git
          - zsh

    - name: copy wallpaper file
      copy:
        src: files/wallpaper.jpg
        dest: /usr/share/backgrounds/wallpaper.jpg
        owner: root
        group: root

    - name: set wallpaper
      become_user: zulu
      dconf:
        key: "/org/gnome/desktop/background/picture-uri"
        value: "'file:///usr/share/backgrounds/wallpaper.jpg'"

    - name: set wallpaper position
      become_user: zulu
      dconf:
        key: "/org/gnome/desktop/background/picture-options"
        value: "'fit'"

    - name: copy .bashrc file
      copy:
        src: files/.bashrc
        dest: /home/zulu/.bashrc
        owner: zulu
        group: zulu

    - name: copy .vimrc file
      copy:
        src: files/.vimrc
        dest: /home/zulu/.vimrc
        owner: zulu
        group: zulu

    - name: copy .zshrc file
      copy:
        src: files/.zshrc
        dest: /home/zulu/.zshrc
        owner: zulu
        group: zulu

    - name: copy .gitconfig file
      copy:
        src: files/.gitconfig
        dest: /home/zulu/.gitconfig
        owner: zulu
        group: zulu

    - name: copy .p10k.zsh file
      copy:
        src: files/.p10k.zsh
        dest: /home/zulu/.p10k.zsh
        owner: zulu
        group: zulu

    - name: copy ruff.toml file
      copy:
        src: files/ruff.toml
        dest: /home/zulu/.config/ruff/ruff.toml
        owner: zulu
        group: zulu
