---
- name: Configure Ubuntu system
  hosts: all
  gather_facts: true
  become: true

  pre_tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600 # Update only if cache is older than 1 hour
      changed_when: false
      when: ansible_facts['distribution'] == 'Ubuntu'

  roles:
    - role: setup_base
      tags: ["base"]
    - role: setup_pipx
      tags: ["pipx"]
    - role: setup_editors
      tags: ["editors"]
    - role: setup_desktop
      tags: ["desktop"]
    - role: setup_dotfiles
      tags: ["dotfiles"]
    - role: setup_fonts
      tags: ["fonts"]
    - role: setup_docker
      tags: ["docker"]
    - role: setup_containerlab
      tags: ["clab"]
    - role: setup_vagrant
      tags: ["vagrant"]
    - role: setup_gnome
      tags: ["gnome"]
      when: ansible_facts['distribution'] == 'Ubuntu'
    - role: setup_netlab
      tags: ["netlab"]
