---
- name: Configure Ubuntu system
  hosts: all
  become: true
  pre_tasks:
    - name: Gather system facts
      ansible.builtin.setup:
      when: ansible_distribution == 'Ubuntu'

    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600 # Update only if cache is older than 1 hour
      changed_when: false
      when: ansible_distribution == 'Ubuntu'

  roles:
    - setup_packages
    - setup_snaps
    - setup_fonts
    - setup_dotfiles
    - setup_terminal
