---
# tasks to complete before running roles
- hosts: all
  become: true
  pre_tasks:
    - name: Update Package Cache
      ansible.builtin.apt: update_cache=yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"

  roles:
    - setup_dotfiles
    - setup_fonts
    - setup_packages
    - setup_snaps
    - setup_terminal
