---
- hosts: all
  connection: local
  become: true
  tasks:
    - name: copy wallpaper file
      copy:
        src: "{{ wallpaper_src }}"
        dest: "{{ wallpaper_dest }}"
        owner: root
        group: root

    - name: set gnome desktop background settings
      become_user: "{{ ansible_user }}"
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - {
            key: "/org/gnome/desktop/background/picture-uri",
            value: "{{ gnome_background_picture_uri }}",
          }
        - {
            key: "/org/gnome/desktop/background/picture-options",
            value: "{{ gnome_background_picture_options }}",
          }
