---
- name: Copy GNOME wallpapers
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
    owner: root
    group: root
  become: true
  loop:
    - {
        src: "ubuntu_wallpaper.jpg",
        dest: "/usr/share/backgrounds/ubuntu_wallpaper.jpg",
      }
    - {
        src: "default_wallpaper.jpg",
        dest: "/usr/share/backgrounds/default_wallpaper.jpg",
      }

- name: Ensure dconf directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  become: true
  loop:
    - /etc/dconf/profile
    - /etc/dconf/db/local.d
    - /etc/dconf/db/gdm.d

- name: Deploy GNOME dconf defaults
  copy:
    src: dconf_gnome.ini
    dest: /etc/dconf/db/local.d/00-gnome-defaults
    owner: root
    group: root
    mode: "0644"
  notify: Update dconf
  become: true

- name: Deploy GDM dconf settings defaults
  copy:
    src: dconf_gdm.ini
    dest: /etc/dconf/db/gdm.d/00-global
    mode: "0644"
    owner: root
    group: root
  notify: Update dconf
  become: true

- name: Copy dconf user profile
  copy:
    src: profile
    dest: /etc/dconf/profile/user
    mode: "0644"
    owner: root
    group: root
  become: true

