---
- name: Deploy GNOME Terminal dconf defaults
  copy:
    src: dconf_terminal.ini
    dest: /etc/dconf/db/local.d/00-gnome-terminal
    owner: root
    group: root
    mode: "0644"
  notify: Update dconf
  become: true
