---
- name: Deploy GNOME dconf defaults
  copy:
    src: dconf_gnome.ini
    dest: /etc/dconf/db/local.d/00-gnome-defaults
    owner: root
    group: root
    mode: "0644"
  notify: Update dconf
  become: true
