---
galaxy_info:
  role_name: setup_desktop
  author: sydasif
  description: Installs desktop GUI packages on Ubuntu
  license: MIT
  min_ansible_version: "2.13"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
        - resolute

  galaxy_tags:
    - ubuntu
    - desktop
    - gui
    - packages

dependencies: []
