---
- name: "Load profile variables for {{ theme_name }}"
  include_vars:
    file: "vars/themes/{{ theme_name }}.yml"

- name: "Ensure terminal profile '{{ profile.visible_name }}' exists and get its UUID"
  ansible.builtin.command: "{{ playbook_dir }}/scripts/configure_gnome_terminal_profile.sh '{{ profile.visible_name }}'"
  register: profile_script_result
  changed_when: "'created:' in profile_script_result.stdout"
  become: true
  become_user: "{{ ansible_user }}"

- name: Set terminal profile UUID fact
  set_fact:
    target_profile_uuid: "{{ profile_script_result.stdout | regex_replace('^(found|created):', '') }}"

- name: "Set terminal profile settings for {{ profile.visible_name }}"
  become: true
  become_user: "{{ ansible_user }}"
  community.general.dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:{{ target_profile_uuid }}/{{ item.key }}"
    value: "{{ item.value | string }}"
  loop: "{{ profile.settings }}"
  when: target_profile_uuid is defined and target_profile_uuid
