---
- name: Ensure snapd is installed
  ansible.builtin.package:
    name: snapd
    state: present

- name: Install snap packages
  community.general.snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic | default(false) }}"
  loop: "{{ snap_packages_to_install }}"
