---
# Base system utilities
base_packages:
  - bat
  - zsh
  - tree
  - curl
  - lsd
  - fzf
  - starship
  - gnome-tweaks
# Python development
python_packages:
  - python3-pip
  - python3-venv
  - python3-psutil
# Virtualization packages
virtualization_packages:
  - bridge-utils
  - cloud-utils
  - genisoimage
  - libguestfs-tools
  - libvirt-clients
  - libvirt-daemon-system
  - libvirt-dev
  - qemu-system-x86
  - qemu-utils
  - virtinst
  - virt-manager
