---
# vars file for setup_containerlab
containerlab_dependencies:
  - curl
containerlab_install_script: https://get.containerlab.dev
vagrantfile_path: /home/{{ ansible_user }}/containerlab-vagrant
vagrant_vm_memory: 2048
vagrant_vm_cpus: 2
