---
- name: install packages
  ansible.builtin.package:
    name: "{{ packages_to_install }}"

- name: check if batcat exists
  ansible.builtin.stat:
    path: /usr/bin/batcat
  register: batcat_stat

- name: ensure bat symlink exists
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: /usr/local/bin/bat
    state: link
    force: true # Ensure the symlink is created/updated
  when:
    - ansible_facts.distribution == 'Ubuntu'
    - ansible_facts.distribution_major_version is version('20.04', '>=')
    - batcat_stat.stat.exists
