---
# CLI / shell utilities
cli_packages:
  - bat
  - zsh
  - tree
  - curl
  - lsd
  - fzf
  - starship
  - git
  - sshpass
  - openvswitch-switch

# Python development (system packages)
python_packages:
  - python3-psutil
