---
- name: Install networklab via pipx
  community.general.pipx:
    name: "{{ netlab_pipx_package }}"
    state: present
    executable: "{{ netlab_pipx_executable }}"
  become: false
  environment: "{{ netlab_pipx_environment }}"

- name: Get networklab injected packages
  community.general.pipx_info:
    name: "{{ netlab_pipx_package }}"
    include_injected: true
    executable: "{{ netlab_pipx_executable }}"
  become: false
  environment: "{{ netlab_pipx_environment }}"
  register: netlab_pipx_info
  failed_when: false

- name: Collect injected package names
  ansible.builtin.set_fact:
    netlab_injected_present: "{{ ((netlab_pipx_info.application | first | default({})).injected | default({})).keys() | list }}"

- name: Inject networklab pinned dependencies
  community.general.pipx:
    name: "{{ netlab_pipx_package }}"
    state: inject
    inject_packages: ["{{ item }}"]
    executable: "{{ netlab_pipx_executable }}"
  become: false
  loop: "{{ netlab_injected_packages }}"
  when: item | regex_replace('^([^<>=!~]+).*', '\\1') | replace('_', '-') | replace('.', '-') not in netlab_injected_present
  environment: "{{ netlab_pipx_environment }}"

- name: Verify networklab installation
  ansible.builtin.command:
    cmd: netlab version
  become: false
  changed_when: false
  failed_when: false
  environment: "{{ netlab_pipx_environment }}"
