---
galaxy_info:
  role_name: setup_containerlab
  author: sydasif
  description: Installs Containerlab and deploys a libvirt Vagrantfile for network labs
  license: MIT
  min_ansible_version: "2.13"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
        - resolute
  galaxy_tags:
    - ubuntu
    - desktop
    - containerlab
    - network
dependencies: []
